### ISSUE TITLE
Grenades do not refill on respawn

### ISSUE THREAD

**Issue by freshvictory** [EECS390IndieTeam/GameProject#22]
If you throw some or all of your grenades you don't get them back when you respawn.

Reproduction Steps:
1. Throw all or some of your grenades
2. Die
3. See that you've permanently lost those grenades

Build information:
Commit e04ddd0

System Information:

OS: All

**Comment by YourGamesBeOver** [comment]
Fixed, I don't remember which commit

**Comment by freshvictory** [comment]
fixed as of 6e2dc53
