### ISSUE TITLE
Non-host players cannot pick up the flag

### ISSUE THREAD

**Issue by freshvictory** [EECS390IndieTeam/GameProject#23]
Reproduction steps:
1. Join a game someone else is hosting
2. Try and run through the flag to pick it up
3. Fail
4. Lose

All Platforms

**Comment by 12wrigja** [comment]
This might be resolved as of commit d0f9173.

**Comment by YourGamesBeOver** [comment]
Resolved as of commit 0cc47c2

**Comment by freshvictory** [comment]
fixed as of 6e2dc53
