### ISSUE TITLE
Upon death you do not drop the flag

### ISSUE THREAD

**Issue by 12wrigja** [EECS390IndieTeam/GameProject#25]
When you die in capture the flag, the flag is not dropped from your player and will move with you when you respawn.

Reproduction Steps:
1. Pick up a flag
2. Die
3. See that the flag is still attached to you when you respawn 

Build information:
Commit d0f9173

System Information:

OS: All

**Comment by YourGamesBeOver** [comment]
Resolved as of commit 0cc47c2

**Comment by JSatterf1579** [comment]
Definitely not fixed in 65384da

Same triggering conditions cause the bug to occur.
Specifically, clients still hold onto the flag while the host does not.

**Comment by freshvictory** [comment]
fixed as of 6e2dc53
