### ISSUE TITLE
Flag lag as the Client

### ISSUE THREAD

**Issue by 12wrigja** [EECS390IndieTeam/GameProject#27]
As the client, the flag will lag behind you when you pick it up.

Reproduction Steps:
1.) Start a CTF Game
2.) Pickup the flag as a non-player
3.) Look around you and notice that as you move the flag you picked up is following you.

Present in Build/Commit: d0f9173

**Comment by YourGamesBeOver** [comment]
Resolved as of commit 0cc47c2

**Comment by freshvictory** [comment]
fixed as of 6e2dc53
