### ISSUE TITLE
Gun does not disappear if the client picks up the flag

### ISSUE THREAD

**Issue by 12wrigja** [EECS390IndieTeam/GameProject#28]
As the server if you pick up the flag your gun disappears to show just the flag. As the client, this does not happen.

Steps:
1.) Start CTF
2.) As a client, pick up the flag
3.) notice that you are still holding your gun (or that if you are holding the flag that your gun does not disappear)

Present in Build / Commit: d0f9173

**Comment by YourGamesBeOver** [comment]
Resolved as of commit 0cc47c2

**Comment by freshvictory** [comment]
fixed as of 6e2dc53
