### ISSUE TITLE
Flag scoring when your flag is NOT returned

### ISSUE THREAD

**Issue by 12wrigja** [EECS390IndieTeam/GameProject#32]
You can capture the flag when your flag is not at your base

Steps:
1.) Start a ctf game with two people
2.) move both flags from their start points
3.) go and move into the enemie's flag capture point and notice that you get the point
     - might be hard to notice due to the ui bug present in #24. 

Present in build: d0f9173

**Comment by freshvictory** [comment]
fixed as of 6e2dc53
