### ISSUE TITLE
You cannot pickup your own flag to return it.

### ISSUE THREAD

**Issue by 12wrigja** [EECS390IndieTeam/GameProject#33]
As stated, if your flag is moved from your base you cannot pick it up to return it. This is partially to do with bug #25, although it also does not work if the other team drops the flag.

Steps:
1.) start ctf with multiple people
2.) have a player on the opposing team move the flag from the base and drop it somewhere using left click
3.) try and pick up the flag as a member of the flag's team.

Present in build d0f9173

**Comment by YourGamesBeOver** [comment]
Resolved as of commit 0cc47c2

**Comment by freshvictory** [comment]
fixed as of 6e2dc53
